// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gigxMN.proto

package gigxMN

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId             string   `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedDate          string   `protobuf:"bytes,6,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate          string   `protobuf:"bytes,7,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	FileHash             string   `protobuf:"bytes,8,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	IsBuried             bool     `protobuf:"varint,9,opt,name=is_buried,json=isBuried,proto3" json:"is_buried,omitempty"`
	IsFolderFile         bool     `protobuf:"varint,10,opt,name=is_folder_file,json=isFolderFile,proto3" json:"is_folder_file,omitempty"`
	IsStarred            bool     `protobuf:"varint,11,opt,name=is_starred,json=isStarred,proto3" json:"is_starred,omitempty"`
	IsTrash              bool     `protobuf:"varint,12,opt,name=is_trash,json=isTrash,proto3" json:"is_trash,omitempty"`
	IsDeleted            bool     `protobuf:"varint,13,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *File) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *File) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *File) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

func (m *File) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *File) GetIsBuried() bool {
	if m != nil {
		return m.IsBuried
	}
	return false
}

func (m *File) GetIsFolderFile() bool {
	if m != nil {
		return m.IsFolderFile
	}
	return false
}

func (m *File) GetIsStarred() bool {
	if m != nil {
		return m.IsStarred
	}
	return false
}

func (m *File) GetIsTrash() bool {
	if m != nil {
		return m.IsTrash
	}
	return false
}

func (m *File) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{1}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type HelloRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{2}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{3}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UploadFileRequest struct {
	File                 *Chunk   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileRequest) Reset()         { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()    {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{4}
}

func (m *UploadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileRequest.Unmarshal(m, b)
}
func (m *UploadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileRequest.Marshal(b, m, deterministic)
}
func (m *UploadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileRequest.Merge(m, src)
}
func (m *UploadFileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadFileRequest.Size(m)
}
func (m *UploadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileRequest proto.InternalMessageInfo

func (m *UploadFileRequest) GetFile() *Chunk {
	if m != nil {
		return m.File
	}
	return nil
}

type UploadFileResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileResponse) Reset()         { *m = UploadFileResponse{} }
func (m *UploadFileResponse) String() string { return proto.CompactTextString(m) }
func (*UploadFileResponse) ProtoMessage()    {}
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{5}
}

func (m *UploadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileResponse.Unmarshal(m, b)
}
func (m *UploadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileResponse.Marshal(b, m, deterministic)
}
func (m *UploadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileResponse.Merge(m, src)
}
func (m *UploadFileResponse) XXX_Size() int {
	return xxx_messageInfo_UploadFileResponse.Size(m)
}
func (m *UploadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileResponse proto.InternalMessageInfo

func (m *UploadFileResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LongGreetRequest struct {
	Greeting             *Chunk   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetRequest) Reset()         { *m = LongGreetRequest{} }
func (m *LongGreetRequest) String() string { return proto.CompactTextString(m) }
func (*LongGreetRequest) ProtoMessage()    {}
func (*LongGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{6}
}

func (m *LongGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetRequest.Unmarshal(m, b)
}
func (m *LongGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetRequest.Marshal(b, m, deterministic)
}
func (m *LongGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetRequest.Merge(m, src)
}
func (m *LongGreetRequest) XXX_Size() int {
	return xxx_messageInfo_LongGreetRequest.Size(m)
}
func (m *LongGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetRequest proto.InternalMessageInfo

func (m *LongGreetRequest) GetGreeting() *Chunk {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type LongGreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetResponse) Reset()         { *m = LongGreetResponse{} }
func (m *LongGreetResponse) String() string { return proto.CompactTextString(m) }
func (*LongGreetResponse) ProtoMessage()    {}
func (*LongGreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{7}
}

func (m *LongGreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetResponse.Unmarshal(m, b)
}
func (m *LongGreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetResponse.Marshal(b, m, deterministic)
}
func (m *LongGreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetResponse.Merge(m, src)
}
func (m *LongGreetResponse) XXX_Size() int {
	return xxx_messageInfo_LongGreetResponse.Size(m)
}
func (m *LongGreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetResponse proto.InternalMessageInfo

func (m *LongGreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type InsertFileRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertFileRequest) Reset()         { *m = InsertFileRequest{} }
func (m *InsertFileRequest) String() string { return proto.CompactTextString(m) }
func (*InsertFileRequest) ProtoMessage()    {}
func (*InsertFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{8}
}

func (m *InsertFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertFileRequest.Unmarshal(m, b)
}
func (m *InsertFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertFileRequest.Marshal(b, m, deterministic)
}
func (m *InsertFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertFileRequest.Merge(m, src)
}
func (m *InsertFileRequest) XXX_Size() int {
	return xxx_messageInfo_InsertFileRequest.Size(m)
}
func (m *InsertFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertFileRequest proto.InternalMessageInfo

func (m *InsertFileRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type InsertFileResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertFileResponse) Reset()         { *m = InsertFileResponse{} }
func (m *InsertFileResponse) String() string { return proto.CompactTextString(m) }
func (*InsertFileResponse) ProtoMessage()    {}
func (*InsertFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2b8a3c64eb280d4, []int{9}
}

func (m *InsertFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertFileResponse.Unmarshal(m, b)
}
func (m *InsertFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertFileResponse.Marshal(b, m, deterministic)
}
func (m *InsertFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertFileResponse.Merge(m, src)
}
func (m *InsertFileResponse) XXX_Size() int {
	return xxx_messageInfo_InsertFileResponse.Size(m)
}
func (m *InsertFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertFileResponse proto.InternalMessageInfo

func (m *InsertFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "gigx.File")
	proto.RegisterType((*Chunk)(nil), "gigx.Chunk")
	proto.RegisterType((*HelloRequest)(nil), "gigx.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "gigx.HelloResponse")
	proto.RegisterType((*UploadFileRequest)(nil), "gigx.UploadFileRequest")
	proto.RegisterType((*UploadFileResponse)(nil), "gigx.UploadFileResponse")
	proto.RegisterType((*LongGreetRequest)(nil), "gigx.LongGreetRequest")
	proto.RegisterType((*LongGreetResponse)(nil), "gigx.LongGreetResponse")
	proto.RegisterType((*InsertFileRequest)(nil), "gigx.InsertFileRequest")
	proto.RegisterType((*InsertFileResponse)(nil), "gigx.InsertFileResponse")
}

func init() { proto.RegisterFile("proto/gigxMN.proto", fileDescriptor_c2b8a3c64eb280d4) }

var fileDescriptor_c2b8a3c64eb280d4 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x6f, 0x12, 0x41,
	0x14, 0x2f, 0x94, 0xc2, 0xf2, 0xa0, 0x8d, 0x8c, 0x49, 0x19, 0x31, 0x2a, 0xdd, 0x98, 0x88, 0xd1,
	0xa0, 0x29, 0xbd, 0x79, 0xd1, 0xb6, 0xb6, 0x25, 0x51, 0x0f, 0xa0, 0x17, 0x2f, 0x9b, 0x2d, 0xf3,
	0x5c, 0x26, 0x6e, 0x77, 0x71, 0x66, 0xd6, 0xe8, 0xd1, 0x6f, 0xe0, 0x47, 0x36, 0xf3, 0x66, 0xb6,
	0x6c, 0xc5, 0xd8, 0x1b, 0xbf, 0x3f, 0x6f, 0x7e, 0xf3, 0xde, 0x63, 0x07, 0xd8, 0x4a, 0xe5, 0x26,
	0x7f, 0x91, 0xc8, 0xe4, 0xc7, 0xfb, 0x0f, 0x63, 0x02, 0xac, 0x61, 0x51, 0xf8, 0x6b, 0x1b, 0x1a,
	0x67, 0x32, 0x45, 0xb6, 0x07, 0x75, 0x29, 0x78, 0x6d, 0x58, 0x1b, 0xb5, 0x67, 0x75, 0x29, 0x58,
	0x1f, 0x5a, 0x85, 0x46, 0x15, 0x49, 0xc1, 0xeb, 0x44, 0x36, 0x2d, 0x9c, 0x0a, 0x76, 0x1f, 0xda,
	0x5f, 0xf2, 0x54, 0x38, 0x69, 0x9b, 0xa4, 0xc0, 0x11, 0x53, 0xc1, 0x18, 0x34, 0xb2, 0xf8, 0x0a,
	0x79, 0x83, 0x78, 0xfa, 0xcd, 0x86, 0xd0, 0x11, 0xa8, 0x17, 0x4a, 0xae, 0x8c, 0xcc, 0x33, 0xbe,
	0x43, 0x52, 0x95, 0x62, 0x07, 0xd0, 0x5d, 0x28, 0x8c, 0x0d, 0x8a, 0x48, 0xc4, 0x06, 0x79, 0xd3,
	0x59, 0x3c, 0x77, 0x1a, 0x1b, 0xb4, 0x96, 0x62, 0x25, 0xd6, 0x96, 0x96, 0xb3, 0x78, 0x8e, 0x2c,
	0xf6, 0x62, 0x32, 0xc5, 0x68, 0x19, 0xeb, 0x25, 0x0f, 0xfc, 0xc5, 0x64, 0x8a, 0x17, 0xb1, 0x5e,
	0x5a, 0x51, 0xea, 0xe8, 0xb2, 0x50, 0x12, 0x05, 0x6f, 0x0f, 0x6b, 0xa3, 0x60, 0x16, 0x48, 0x7d,
	0x4c, 0x98, 0x3d, 0x86, 0x3d, 0xa9, 0x23, 0xdf, 0x95, 0x2d, 0xe1, 0x40, 0x8e, 0xae, 0xd4, 0x67,
	0x44, 0xd2, 0x84, 0x1e, 0x00, 0x48, 0x1d, 0x69, 0x13, 0x2b, 0x85, 0x82, 0x77, 0xc8, 0xd1, 0x96,
	0x7a, 0xee, 0x08, 0x76, 0x0f, 0x02, 0xa9, 0x23, 0xa3, 0x6c, 0x7a, 0x97, 0xc4, 0x96, 0xd4, 0x1f,
	0x2d, 0xf4, 0x95, 0x02, 0x53, 0x34, 0x28, 0xf8, 0x6e, 0x59, 0x79, 0xea, 0x88, 0xf0, 0x00, 0x76,
	0x4e, 0x96, 0x45, 0xf6, 0x95, 0x71, 0x68, 0x9d, 0xe4, 0x99, 0xc1, 0xcc, 0xd0, 0x22, 0xba, 0xb3,
	0x12, 0x86, 0x23, 0xe8, 0x5e, 0x60, 0x9a, 0xe6, 0x33, 0xfc, 0x56, 0xa0, 0x36, 0xd6, 0x79, 0x85,
	0x5a, 0xc7, 0x09, 0xfa, 0x95, 0x95, 0x30, 0x7c, 0x0a, 0xbb, 0xde, 0xa9, 0x57, 0x79, 0xa6, 0xf1,
	0x3f, 0xd6, 0x23, 0xe8, 0x7d, 0x5a, 0xa5, 0x79, 0x2c, 0x6c, 0x7b, 0xe5, 0xc9, 0x8f, 0xa0, 0x41,
	0x13, 0xb0, 0xde, 0xce, 0x61, 0x67, 0x6c, 0xff, 0x25, 0x63, 0xba, 0xde, 0x8c, 0x84, 0xf0, 0x39,
	0xb0, 0x6a, 0x95, 0x4f, 0xd9, 0x87, 0xa6, 0x42, 0x5d, 0xa4, 0xc6, 0x87, 0x78, 0x14, 0xbe, 0x82,
	0x3b, 0xef, 0xf2, 0x2c, 0x39, 0x57, 0x88, 0xa6, 0x8c, 0x78, 0x02, 0x41, 0x62, 0xb1, 0xcc, 0x92,
	0x7f, 0xc5, 0x5c, 0x8b, 0xe1, 0x33, 0xe8, 0x55, 0x8a, 0x6f, 0x49, 0x9a, 0x40, 0x6f, 0x9a, 0x69,
	0x54, 0xa6, 0xda, 0xcd, 0xc3, 0x1b, 0xdd, 0x80, 0x8b, 0x21, 0x83, 0x6b, 0xe6, 0x08, 0x58, 0xb5,
	0xc8, 0x47, 0xdc, 0x52, 0x75, 0xf8, 0xbb, 0x0e, 0xbb, 0xe7, 0xf4, 0x2d, 0xcd, 0x51, 0x7d, 0x97,
	0x0b, 0x64, 0x13, 0x08, 0xe6, 0xf1, 0x4f, 0x1a, 0x3c, 0x63, 0xce, 0x5f, 0xdd, 0xd7, 0xe0, 0xee,
	0x0d, 0xce, 0xc7, 0xbc, 0x05, 0x58, 0x4f, 0x92, 0xf5, 0x9d, 0x65, 0x63, 0x23, 0x03, 0xbe, 0x29,
	0xb8, 0x03, 0xc2, 0xad, 0x51, 0xed, 0x65, 0x8d, 0xbd, 0x01, 0x58, 0xf7, 0x50, 0x1e, 0xb3, 0x31,
	0x8a, 0xf2, 0x98, 0xcd, 0x76, 0xc3, 0x2d, 0xf6, 0x1a, 0xda, 0xd7, 0x83, 0x66, 0xfb, 0xce, 0xf8,
	0xf7, 0xda, 0x06, 0xfd, 0x0d, 0x7e, 0x7d, 0x8d, 0xe3, 0xe0, 0x73, 0xd3, 0xbd, 0x2e, 0x97, 0x4d,
	0x7a, 0x5e, 0x26, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xe9, 0x36, 0x5c, 0x74, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GigxMNServiceClient is the client API for GigxMNService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GigxMNServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// BiDi Streaming
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (GigxMNService_UploadFileClient, error)
	InsertFile(ctx context.Context, in *InsertFileRequest, opts ...grpc.CallOption) (*InsertFileResponse, error)
	LongGreet(ctx context.Context, opts ...grpc.CallOption) (GigxMNService_LongGreetClient, error)
}

type gigxMNServiceClient struct {
	cc *grpc.ClientConn
}

func NewGigxMNServiceClient(cc *grpc.ClientConn) GigxMNServiceClient {
	return &gigxMNServiceClient{cc}
}

func (c *gigxMNServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxMNService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxMNServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (GigxMNService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GigxMNService_serviceDesc.Streams[0], "/gigx.GigxMNService/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &gigxMNServiceUploadFileClient{stream}
	return x, nil
}

type GigxMNService_UploadFileClient interface {
	Send(*UploadFileRequest) error
	Recv() (*UploadFileResponse, error)
	grpc.ClientStream
}

type gigxMNServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *gigxMNServiceUploadFileClient) Send(m *UploadFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gigxMNServiceUploadFileClient) Recv() (*UploadFileResponse, error) {
	m := new(UploadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gigxMNServiceClient) InsertFile(ctx context.Context, in *InsertFileRequest, opts ...grpc.CallOption) (*InsertFileResponse, error) {
	out := new(InsertFileResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxMNService/InsertFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxMNServiceClient) LongGreet(ctx context.Context, opts ...grpc.CallOption) (GigxMNService_LongGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GigxMNService_serviceDesc.Streams[1], "/gigx.GigxMNService/LongGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &gigxMNServiceLongGreetClient{stream}
	return x, nil
}

type GigxMNService_LongGreetClient interface {
	Send(*LongGreetRequest) error
	CloseAndRecv() (*LongGreetResponse, error)
	grpc.ClientStream
}

type gigxMNServiceLongGreetClient struct {
	grpc.ClientStream
}

func (x *gigxMNServiceLongGreetClient) Send(m *LongGreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gigxMNServiceLongGreetClient) CloseAndRecv() (*LongGreetResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongGreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GigxMNServiceServer is the server API for GigxMNService service.
type GigxMNServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	// BiDi Streaming
	UploadFile(GigxMNService_UploadFileServer) error
	InsertFile(context.Context, *InsertFileRequest) (*InsertFileResponse, error)
	LongGreet(GigxMNService_LongGreetServer) error
}

func RegisterGigxMNServiceServer(s *grpc.Server, srv GigxMNServiceServer) {
	s.RegisterService(&_GigxMNService_serviceDesc, srv)
}

func _GigxMNService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxMNServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxMNService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxMNServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxMNService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GigxMNServiceServer).UploadFile(&gigxMNServiceUploadFileServer{stream})
}

type GigxMNService_UploadFileServer interface {
	Send(*UploadFileResponse) error
	Recv() (*UploadFileRequest, error)
	grpc.ServerStream
}

type gigxMNServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *gigxMNServiceUploadFileServer) Send(m *UploadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gigxMNServiceUploadFileServer) Recv() (*UploadFileRequest, error) {
	m := new(UploadFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GigxMNService_InsertFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxMNServiceServer).InsertFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxMNService/InsertFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxMNServiceServer).InsertFile(ctx, req.(*InsertFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxMNService_LongGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GigxMNServiceServer).LongGreet(&gigxMNServiceLongGreetServer{stream})
}

type GigxMNService_LongGreetServer interface {
	SendAndClose(*LongGreetResponse) error
	Recv() (*LongGreetRequest, error)
	grpc.ServerStream
}

type gigxMNServiceLongGreetServer struct {
	grpc.ServerStream
}

func (x *gigxMNServiceLongGreetServer) SendAndClose(m *LongGreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gigxMNServiceLongGreetServer) Recv() (*LongGreetRequest, error) {
	m := new(LongGreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GigxMNService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gigx.GigxMNService",
	HandlerType: (*GigxMNServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GigxMNService_SayHello_Handler,
		},
		{
			MethodName: "InsertFile",
			Handler:    _GigxMNService_InsertFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _GigxMNService_UploadFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LongGreet",
			Handler:       _GigxMNService_LongGreet_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gigxMN.proto",
}
